---
- name: Get Openshift Pods from gw-dev namespace
  hosts: localhost
  gather_facts: no
  collections: 
    - community.kubernetes
  vars:
    namespace: 
    
  tasks:
  - name: Get gateway pods
    kubernetes.core.k8s_info:
      kind: Pod
      namespace: '{{ namespace }}'
    register: pod_list
  - debug:
      var: pod_list.resources 
